version: '2.4'
services:
  ui:
    build:
      context: ../knock_knock_frontend
      dockerfile: docker/development/Dockerfile
    container_name: knock-knock-frontend
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - knock-knock-api-net
    tty: true
    stdin_open: true
    volumes:
      - ../knock_knock_frontend:/home/nodeuser/app
    depends_on:
      - api

  api:
    build:
      context: ../knock_knock
      dockerfile: docker/development/Dockerfile
    container_name: knock-knock-api
    ports:
      - 8000:8000
    env_file:
      - ../knock_knock/env/development/.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../knock_knock:/home/django/app
    networks:
      - knock-knock-api-net
      - knock-knock-db-net
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    network_mode: brigde
    env_file:
      - ../knock_knock/env/development/.db.env
    ports:
      - 5433:5432
    container_name: knock-knock-db
    networks:
      - knock-knock-db-net
    volumes:
      - knock-knock-data-storage:/var/lib/postgresql/data

networks:
  knock-knock-api-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  knock-knock-db-net:
    driver: brigde

volumes:
  knock-knock-data-storage:
